//Fichier contenant toutes les macroconstantes correspondant aux codes d'erreur renvoyées

#define ERR_NO_FREE_INODE  -10
#define ERR_ROOT_ALRDY_CREATED  -11
#define ERR_PARENT_NOT_FOLDER -12
#define ERR_ROOT_WRONG_ID -13
#define ERR_DIRECTORY_FULL -14
#define ERR_UNUSUED_INODE -15
#define ERR_DIRECTORY_NOT_EMPTY -16
#define ERR_INODE_ID_NOT_FOUND_IN_FOLDER -17
#define ERR_INODE_IS_NOT_A_FOLDER -18
#define ERR_NAME_ALREADY_USED_IN_FOLDER -19
#define ERR_UNUSUED_PARENT_INODE -20
#define ERR_WRONG_TYPE -21
#define ERR_EMPTY_FOLDER -22
#define ERR_FOLDER_NOT_FOUND -23
#define ERR_DESTINATION_NOT_A_FOLDER -24
#define EXIT -25
#define ERR_TOO_MANY_ARGUMENTS -26
#define ERR_NO_ARGUMENT -27
#define ERR_NOT_ENOUGH_ARGUMENTS -28
#define ERR_TARGET_NOT_FOUND -29
#define ERR_COMMAND_DOESNT_EXIST -30
